version: '2.4'
services:
  vscode-server:
    build:
      context: ./code-server
    environment:
        - PGID=1000
        - TZ=Europe/London
        - PASSWORD=toto
        - SUDO_PASSWORD=toto
    volumes:
      - ./config-vscode:/config
      - workspace:/workspace
    ports:
      - "8080:8443"
    restart: always

volumes:
  workspace: