# Scratch n'est pas une image mais un mot clef pour
# spécifier une image vide
FROM scratch
# MAINTAINER est obsolete
LABEL MAINTAINER="philippe.bouamriou@thalesgroup.com"

# hello est une application statique
ADD hello /
CMD [ "/hello" ]